Make DynaMOSA write to a csv file.
When the new_statistics property of EvoSuite is enabled, then some classes start to throw NoClassDefFoundError and MarshalException. Therefore, to record coverage over time, I introduced my own csv writing capability.

Something might need addressing in the future. E.g., better exception handler, or ideally fix the problems with the EvoSuite CSV backend because my approach might slightly hinder the search due to the time spent writing to file.